// Code generated by dagnabit; DO NOT EDIT.

package yaml_diagnostic

import internal "github.com/amarbel-llc/tap/go/internal/alfa/yaml_diagnostic"

type (
	YAMLDiagnostic = internal.YAMLDiagnostic
)

var (
	SanitizeYAMLValue = internal.SanitizeYAMLValue
	WriteDiagnostics  = internal.WriteDiagnostics
)
