// Code generated by dagnabit; DO NOT EDIT.

package gotest

import internal "github.com/amarbel-llc/tap/go/internal/charlie/gotest"

// ConvertGoTest reads go test -json events from r and writes TAP-14 to w.
// If verbose is true, passing tests include output diagnostics.
// If skipEmpty is true, packages with no tests emit a SKIP directive instead of not ok.
// If color is true, ok/not ok keywords are ANSI-colorized.
// Returns an exit code: 0 for all pass, 1 for any failure, 2 for build errors.
var ConvertGoTest = internal.ConvertGoTest
