// Code generated by dagnabit; DO NOT EDIT.

package writer

import internal "github.com/amarbel-llc/tap/go/internal/bravo/writer"

type (
	OutputBlockWriter = internal.OutputBlockWriter
	TestPoint         = internal.TestPoint
	Writer            = internal.Writer
)

var (
	NewColorWriter  = internal.NewColorWriter
	NewLocaleWriter = internal.NewLocaleWriter
	NewWriter       = internal.NewWriter
)
