// Code generated by dagnabit; DO NOT EDIT.

package exec_parallel

import internal "github.com/amarbel-llc/tap/go/internal/delta/exec_parallel"

type (
	ExecOption        = internal.ExecOption
	ExecResult        = internal.ExecResult
	Executor          = internal.Executor
	GoroutineExecutor = internal.GoroutineExecutor
)

var (
	ConvertExec                   = internal.ConvertExec
	ConvertExecParallel           = internal.ConvertExecParallel
	ConvertExecParallelWithStatus = internal.ConvertExecParallelWithStatus
	WithSpinner                   = internal.WithSpinner
)
