// Code generated by dagnabit; DO NOT EDIT.

package style

import internal "github.com/amarbel-llc/tap/go/internal/0/style"

var (
	Green  = internal.Green
	Red    = internal.Red
	Yellow = internal.Yellow
)
