// Code generated by dagnabit; DO NOT EDIT.

package ndjson

import internal "github.com/amarbel-llc/tap/go/internal/bravo/ndjson"

type (
	Aggregator        = internal.Aggregator
	Output            = internal.Output
	TestRecord        = internal.TestRecord
	SummaryRecord     = internal.SummaryRecord
	BailoutRecord     = internal.BailoutRecord
	DirectiveValue    = internal.DirectiveValue
	SummaryDiagnostic = internal.SummaryDiagnostic
)

var (
	NewAggregator = internal.NewAggregator
	WriteAll      = internal.WriteAll
	WriteSplit    = internal.WriteSplit
)
