// Code generated by dagnabit; DO NOT EDIT.

package classify

import internal "github.com/amarbel-llc/tap/go/internal/0/classify"

type (
	LineKind = internal.LineKind
)

var (
	ClassifyLine       = internal.ClassifyLine
	OutputHeaderRegexp = internal.OutputHeaderRegexp
	PlanRegexp         = internal.PlanRegexp
	PragmaRegexp       = internal.PragmaRegexp
	StripANSI          = internal.StripANSI
	StripNonSGR        = internal.StripNonSGR
	TestPointRegexp    = internal.TestPointRegexp
)

const (
	LineBailOut        = internal.LineBailOut
	LineComment        = internal.LineComment
	LineEmpty          = internal.LineEmpty
	LineOutputHeader   = internal.LineOutputHeader
	LinePlan           = internal.LinePlan
	LinePragma         = internal.LinePragma
	LineSubtestComment = internal.LineSubtestComment
	LineTestPoint      = internal.LineTestPoint
	LineUnknown        = internal.LineUnknown
	LineVersion        = internal.LineVersion
	LineYAMLEnd        = internal.LineYAMLEnd
	LineYAMLStart      = internal.LineYAMLStart
)
