// Code generated by dagnabit; DO NOT EDIT.

package diagnostic

import internal "github.com/amarbel-llc/tap/go/internal/0/diagnostic"

type (
	BailOutResult      = internal.BailOutResult
	Diagnostic         = internal.Diagnostic
	Directive          = internal.Directive
	Event              = internal.Event
	EventType          = internal.EventType
	OutputHeaderResult = internal.OutputHeaderResult
	PlanResult         = internal.PlanResult
	PragmaResult       = internal.PragmaResult
	Severity           = internal.Severity
	Summary            = internal.Summary
	TestPointResult    = internal.TestPointResult
)

const (
	DirectiveNone       = internal.DirectiveNone
	DirectiveSkip       = internal.DirectiveSkip
	DirectiveTodo       = internal.DirectiveTodo
	EventBailOut        = internal.EventBailOut
	EventComment        = internal.EventComment
	EventOutputHeader   = internal.EventOutputHeader
	EventOutputLine     = internal.EventOutputLine
	EventPlan           = internal.EventPlan
	EventPragma         = internal.EventPragma
	EventSubtestEnd     = internal.EventSubtestEnd
	EventSubtestStart   = internal.EventSubtestStart
	EventTestPoint      = internal.EventTestPoint
	EventUnknown        = internal.EventUnknown
	EventVersion        = internal.EventVersion
	EventYAMLDiagnostic = internal.EventYAMLDiagnostic
	SeverityError       = internal.SeverityError
	SeverityWarning     = internal.SeverityWarning
)
