// Code generated by dagnabit; DO NOT EDIT.

package diagnostic

import internal "code.linenisgreat.com/tap/go/internal/0/diagnostic"

// BailOutResult holds parsed data from a bail out line.
type BailOutResult = internal.BailOutResult

// Diagnostic represents a single validation problem found in TAP input.
type Diagnostic = internal.Diagnostic

// Directive represents a TAP test point directive.
type Directive = internal.Directive

// Event represents a single parsed TAP element.
type Event = internal.Event

// EventType classifies a parsed TAP line.
type EventType = internal.EventType

// OutputHeaderResult holds parsed data from an Output Block header.
type OutputHeaderResult = internal.OutputHeaderResult

// PlanResult holds parsed data from a plan line.
type PlanResult = internal.PlanResult

// PragmaResult holds parsed data from a pragma line.
type PragmaResult = internal.PragmaResult

// Severity indicates the severity of a validation diagnostic.
type Severity = internal.Severity

// Summary provides aggregate results after parsing a TAP document.
type Summary = internal.Summary

// TestPointResult holds parsed data from a test point line.
type TestPointResult = internal.TestPointResult

const (
	DirectiveNone       = internal.DirectiveNone
	DirectiveSkip       = internal.DirectiveSkip
	DirectiveTodo       = internal.DirectiveTodo
	EventBailOut        = internal.EventBailOut
	EventComment        = internal.EventComment
	EventOutputHeader   = internal.EventOutputHeader
	EventOutputLine     = internal.EventOutputLine
	EventPlan           = internal.EventPlan
	EventPragma         = internal.EventPragma
	EventSubtestEnd     = internal.EventSubtestEnd
	EventSubtestStart   = internal.EventSubtestStart
	EventTestPoint      = internal.EventTestPoint
	EventUnknown        = internal.EventUnknown
	EventVersion        = internal.EventVersion
	EventYAMLDiagnostic = internal.EventYAMLDiagnostic
	SeverityError       = internal.SeverityError
	SeverityWarning     = internal.SeverityWarning
)
