// Code generated by dagnabit; DO NOT EDIT.

package parse

import internal "github.com/amarbel-llc/tap/go/internal/alfa/parse"

var (
	ParseBailOut          = internal.ParseBailOut
	ParsePlan             = internal.ParsePlan
	ParsePlanWithSep      = internal.ParsePlanWithSep
	ParsePragma           = internal.ParsePragma
	ParseTestPoint        = internal.ParseTestPoint
	ParseTestPointWithSep = internal.ParseTestPointWithSep
)
