// Code generated by dagnabit; DO NOT EDIT.

package reader

import internal "code.linenisgreat.com/tap/go/internal/bravo/reader"

// Reader is a streaming TAP-14 parser and validator.
type Reader = internal.Reader

// NewReader creates a new TAP-14 reader from the given input.
var NewReader = internal.NewReader
