// Code generated by dagnabit; DO NOT EDIT.

package reader

import internal "github.com/amarbel-llc/tap/go/internal/bravo/reader"

type (
	Reader = internal.Reader
)

var (
	NewReader = internal.NewReader
)
