// Code generated by dagnabit; DO NOT EDIT.

package operation_writer

import internal "github.com/amarbel-llc/tap/go/internal/charlie/operation_writer"

type (
	OperationWriter = internal.OperationWriter
)

var (
	NewOperationWriter = internal.NewOperationWriter
)
