// Code generated by dagnabit; DO NOT EDIT.

package reformat

import internal "code.linenisgreat.com/tap/go/internal/alfa/reformat"

// ReformatTAP reads raw TAP (with or without a version line) from r and
// re-emits it as TAP version 14 on w. When color is true, ok/not ok/skip/
// todo/bail out tokens are wrapped in ANSI SGR sequences.
var ReformatTAP = internal.ReformatTAP
